# --------------------------------
# pmon2 config
# --------------------------------

# data dir, such as db data
data: "/etc/pmon2/data"

# logs dir
logs: "/var/log/pmon2/log"

# socket file
sock: "/var/run/pmon2/pmon2.sock"



